# ポートを変更
server:
  port : 8888

# DB接続情報
spring:
  datasource:
    url:  jdbc:postgresql://192.168.99.100:5432/test_db
    username: postgres
    password: P@ssw0rd
    driverClassName: org.postgresql.Driver
